alg = input('digite algo: ')
print(('o tipo primitivo desse valor é'), type(alg))
print('só tem espaço?', alg.isspace())
print('é numero?', alg.isnumeric())
print('é alphabetico?', alg.isalpha())
print('é alphanumerico?', alg.isalnum())
print('é maiuscula?', alg.isupper())
print('é minuscula?', alg.islower())
print('é capitalizado?', alg.istitle())
